export const data = [
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
    {
        id: 1,
        mainCategory: "Notebook",
        category: "Apple",
        imgPng: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img1: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img2: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        img3: "https://hradec.rozhlas.cz/sites/default/files/images/063e49afff550bde4fe6a9a94bab38d3.jpg",
        text1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit fugiat labore temporibus vero doloremque quisquam ducimus, expedita doloribus minus earum commodi deleniti nemo tempora, possimus maxime vel culpa. Eos, sequi!",
        text2: "Lorem sdfiasld lds jlk alds lsdf",
        new: true,

    },
]